version: '3.8'

services:
  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: awesomeapi/gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
